#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE $CM_DB_NAME;
    CREATE USER "$CM_DB_USER" WITH PASSWORD '$CM_DB_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $CM_DB_NAME TO "$CM_DB_USER";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$CM_DB_NAME" <<-EOSQL
    GRANT ALL ON SCHEMA public TO "$CM_DB_USER";
    ALTER SCHEMA public OWNER TO "$CM_DB_USER";
    CREATE EXTENSION IF NOT EXISTS vector;
EOSQL
