#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE $AIAVATAR_DB_NAME;
    CREATE USER "$AIAVATAR_DB_USER" WITH PASSWORD '$AIAVATAR_DB_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $AIAVATAR_DB_NAME TO "$AIAVATAR_DB_USER";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$AIAVATAR_DB_NAME" <<-EOSQL
    GRANT ALL ON SCHEMA public TO "$AIAVATAR_DB_USER";
    ALTER SCHEMA public OWNER TO "$AIAVATAR_DB_USER";
EOSQL
